# Generated by Django 3.2.2 on 2021-05-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
