# Generated by Django 3.2.2 on 2021-05-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacter',
        ),
    ]
