# Generated by Django 3.2.2 on 2021-05-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_contacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cender',
        ),
    ]
