# Generated by Django 3.2.2 on 2021-05-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_user_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='lastName',
        ),
    ]
